apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "netbank-oa.fullname" . }}-ui
  labels:
    app: {{ template "netbank-oa.name" . }}-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "netbank-oa.name" . }}-ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.internalPort }}
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
    {{- if .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.ui.nodeSelector | indent 8 }}
    {{- end }}

