apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-mysql
  labels:
    app: {{ template "fullname" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MYSQL_ROOT_PASSWORD: {{ default "root123456" .Values.mysql.rootPassword | quote }}
