apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    app: {{ template "fullname" . }}-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CONFIG_PATH: /etc/ui/app.conf
  LOG_LEVEL: {{ default "debug" .Values.log_level | quote }}
  UI_SECRET: {{ default "R0pgaboUszpAkhQ0" .Values.ui_secret | quote }}
  JOBSERVICE_SECRET: {{ default "l5wzTaD2RyuwKIIw" .Values.jobservice_secret | quote }}
  GODEBUG: {{ default "netdns=cgo" .Values.godebug | quote }}
  SECRET_KEY: {{ default "lY7sfY5AwPZtcsTz" .Values.secret_key | quote }}
  ADMINSERVER_URL: http://{{ template "fullname" . }}-adminserver
  config: |
    appname = {{ template "fullname" . }}-registry
    runmode = dev
    [lang]
    types = en-US|zh-CN
    names = en-US|zh-CN
    [dev]
    httpport = 80
    [mail]
    host = {{ default "smtp.mydomain.com" .Values.email_host | quote }}
    port = {{ default "645" .Values.email_port | quote }}
    username = {{ default "sample_admin@mydomain.com" .Values.email_usr | quote }}
    password = {{ default "abc" .Values.email_pwd | quote }}
    ssl = {{ default "true" .Values.email_ssl | quote }}
    from = {{ default "admin <sample_admin@mydomain.com>" .Values.email_pwd | quote }}
  pkey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEArJ1j9i5dXL9Ef3aVdwrtc7JCizrSmryKxl5JkDP1bLcq45BZ
    1R5Ti/l6Wku8APgYfcJ3AoGUKPbq+z43HX9NV+pBNDS3ltqcXJws6BhTINCVnXKB
    NW2MfElnZDCPPE5pwdDnTIrEoC2bc2D7t0wwOuNSFrkLx0O4PUiizwuCS5fJTc/M
    DirrM3GdRyDEwhCt/kP2l3/2AaFhRVS2UMWusVubMsiow7uzlcm6mR0DqbFElqE1
    /SraDrTP3SEWA4SeiTI8Nqi+B9VV0OByFg068z9VIqKWMQ366gsqQOmE4+22qJjJ
    n5lM+M3felXWPSeLimxhwHOUeu25crURS+tl4y1hQXXLwEEZoYgtDpnCmWknJDCV
    WRHBJY99Q2aOxlS9D2BAY+74p2V6fKfExCOr7qu+Y5Xn/F+wnGpe5GadMQU763ba
    id6WeVqjlua8RK0CEINxk74u/+pgf14eN/LGh4XTNxVpg+TAd/NTJVipXeEc/H3T
    hNJeQFnfsXsSh6YPxBywD2+w9IW9XbV0o15kJb2iTKf/YBzlI3lLZslPouScfr3E
    ZppOWTOC2yMCGPpa4S7zp5x+H7YAngYfg1sa0YlJVwYvq2zX6OPs3FbW1MCYrgYP
    MMB8anst/ofEn2wBzvh1ktiXRyCwFrt5M3vctpEBplGgEOEpJTj1aNnqsZUCAwEA
    AQKCAgBtVB6tHT6q8MYMyWnvhS9SWTSGhNJBiWuIKs4DFLW8juMOUS5kqpmWDYRu
    ToucPYcdmB7SqonRzFqWmRhFiYzOQyPbUgx58qqYiZ5zvnxgS1yH5a9qzKDvU3q1
    3X/LXYrkZFErjLTvExPjZyjnNs1RbwteMwP/yKeXwTrFUm/LOy8YJqYCzzI7WhmY
    pGua0v+xDRDRcg25iKJYTEhRLnPwB6pr5uXlWyxqkeOq+NKKFynvEdplKFAGgoUp
    dLxBrCzRjszOfeAmi/uXmaEI0IZm7NUaY8om9cjXlgzEImO2Dajkbik9+dXjvFlw
    XY+dGj/qg60CPPJtTcZoncB/ym+0Anyd8FA/ncfWFwADIrG395SL+5VNWQiVfjsw
    QRbnGL6/DETxD+ELOt/OjDAsjjBNOmmPAAPCtyS0j6zHZgznzzeb64lOKM5hmrzj
    5PAuXso30458ucGvp+J8Fmxm/WhyOKWSCVxmK44hlVxfyp5SuUOUQ720YA4f9yNY
    /qWxRTGQq9CgWwBjhMOECkhDQd6qJGG15roIc20Z7OSiP2cp5A95aXBTVNuB2DwB
    CHCapws9Bs16Ca+Im0/hUPE5gSXHxr0q2aQ5Fgxr31+pSGbPA5xPRE+fmEXdkCqN
    wf/jouyLD5xBRIa6pcNpYjuxG118mDy5CiniAmgK82/qqZsO3QKCAQEA1zTaOtn8
    i+oT69Hwk39HBcLY5AX2mR5Y8aqWsgv15NYhWieb1m0AnlW6VVJDwQ0+tqpt2D28
    XUook6MxkS6NGFHF0nsKQkzZ2HeXl09FzsoRXm/+j2LDwkeKhQqbYqQfqyDZzOOr
    pmQgP3GgZbCn4qpWh3NmFwAdqSfVVtDnxldaC12nnFPWJdEqocP7tiZLvLRNBp7V
    9G3fnLo+8yq7T2GBMkd+Iv8wdm9BGwuUO5NXV+Z+oYtmOK9JsUGuB3JKJLWoXNWr
    weN+o2bITjoIYchgg2StVd5K1ndGe1AxqZJb5edNmvHlZnTdSlaEIN5PdBYYFv9Q
    dZoQ85aZoUNeXwKCAQEAzVW6WqMeeOdF1IPbncucF53gBgp/Wc5LVO1O8P472xXP
    GcbfBV7gPU8+RfKivC05aRlnNDo3Qi4iWoVbkrfdsbMPPc17g8NO602sWSncudDD
    k1zSEkidhFEaosOWe7MGnpXBjWJ3MEEQSCgEaNW1i9gyR5l4KntGqz7vpiFLu88Z
    P5/am7YV4AruvObDiGGyMXSH9nycv/A9zJPsgz2CrxTnePZ+DCpBcLtmpGGWz8Cs
    e1JNlq0RoL1oezYyN4iTjTnlAMw7V12eM2cL3I1u0+kx5ToaFDkHlZ2JxY6pIjTy
    PGF0A+a5Pr+hSi0LRFTQR7UI3G2yhfq9fMdNUlYMiwKCAQEAxXHYRuZ4rmW0oUec
    UbcUklSSaaKO/Sy6rf61A+W1VJ6hOvXcJH8dcid1LZKsVxKv1yfGX/9EMtM3Jz0y
    3OC40vczaEk6wFmCBPi0PD6e7Xq3NM3L4AHdWQIKNMXmijnKVFdvfGvlsGNsssit
    QJ8zaOKfQOa/Y5rXm7rQITbJb0/1bTgf7217rHabho8pAZVhJ2DEyq4v3nJwFntK
    Bg/OiqYKwvaU48b9z6uDMC0PcxlbqWnwBIbA4oDwO5Dm+i4BmGySa5oeW2U9au2C
    GUNlLVGKOwLDhWTNhLcqEzkgV1PQvL3ala4ZqkbOQMXfs8hDXV5n+7GDQGJ56wLh
    MPN+QQKCAQBoRFMH+XLc1Bu6iWZ4306ZE3sRtjzq3n2UV5jReVftrUpn/Xt8X6wg
    ld+6ZzZJtfFENDka5UDwIzsgmj1g6Grz9EgWCwTgaMnnZJ7S/BXwaVkWuHiX/jW2
    XfTXl9gPYl5HIyaQ4+JAJ5nb+i4bCgJRS+xkPUMu10CQbroEsz2g1c4tZ7/7d9/t
    z79hPxElbO6ufE0aVjbGpHjNLIRaNF7rBwNvgkOJa9+lHhRF/qQ1RNKRIL7zd1jP
    Nb8bae7gEkNS4IYv/IVZnNlbosT8LvmLNAw5KWLayAbY65FtNz8ddqNXE+l0nbGN
    coO1heAFx8en0f74599Sd3vHI/FYkQd3AoIBAQCkcccax5JU6vw+Bg938TaiGNMb
    UCztN6uDTB8ogcW3epJsah7hrUKN2YeNA/afA67pBXxXAvMycmm79CzPy5MXuz71
    0p5a/P1CI0bVrzOH4bWmWZU4oxrlojkojxJ5DxxS9JUhCbXAVy2H6Owpy2PaZEj3
    xdeVSS0o4Qf+iD3PPYcvu9iRWr5kPapdokfH4TOQqwAIMzRPMf63qqCuZq3ONmp0
    8jWlC4Ppj7OKr26/05WXCu/O3IsLNfXjI4yI4oYtJnfAtbJo1t3fMXW1yHjB47UX
    utb0FBigFBwAzRfJrknaIvImj31mdNCMxFj3k3BIleyJPHC23dgPbKrVrB23
    -----END RSA PRIVATE KEY-----
