apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ui
  labels:
    app: {{ template "fullname" . }}-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ui-app
        image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag}}
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        env:
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: LOG_LEVEL
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: JOBSERVICE_SECRET
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: GODEBUG
          - name: ADMIN_SERVER_URL
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-ui
                key: ADMIN_SERVER_URL
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/ui
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-ui
          items:
          - key: config
            path: app.conf
          - key: pkey
            path: private_key.pem
