apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-jobservice
  labels:
    app: {{ template "fullname" . }}-jobservice
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.jobservice.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-jobservice
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: jobservice-app
        image: {{ .Values.jobservice.image.repository }}:{{ .Values.jobservice.image.tag }}
        imagePullPolicy: {{ .Values.jobservice.image.pullPolicy }}
        resources:
{{ toYaml .Values.jobservice.resources | indent 10 }}
        env:
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-jobservice
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-jobservice
                key: JOBSERVICE_SECRET
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-jobservice
                key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-jobservice
                key: LOG_LEVEL
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
                name: {{ template "fullname" . }}-jobservice
                key: GODEBUG
          - name: ADMIN_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: {{ template "fullname" . }}-jobservice
                key: ADMIN_SERVER_URL
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-jobservice
          items:
          - key: config
            path: app.conf
      - name: logs
      {{- if .Values.jobservice.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-log 
      {{- else }}
        emptyDir: {}
      {{- end -}}
