apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    app: {{ template "name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
  selector:
    app: {{ template "name" . }}-nginx
    release: {{ .Release.Name }}
