apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-mysql
  labels:
    app: {{ template "fullname" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ template "fullname" . }}-mysql
    release: {{ .Release.Name }}
