apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "deltcloud-p1.fullname" . }}
  labels:
    app: {{ template "deltcloud-p1.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data: 
  config: |-
    server.port=8080

    spring.jpa.hibernate.ddl-auto=none
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.url=jdbc:mysql://{{ template "deltcloud-p1.mariadb.fullname" . }}:3306/{{ .Values.mariadb.mariadbDatabase }}
    spring.datasource.username={{ .Values.mariadb.mariadbUser }}
    spring.datasource.password={{ .Values.mariadb.mariadbPassword }}

    spring.jackson.time-zone=GMT+8
    spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
    spring.jpa.show-sql=true
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
