apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: { template "deltcloud-p1.fullname" . }}-user
  labels:
    app: {{ template "deltcloud-p1.name" . }}-user
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.user.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "deltcloud-p1.name" . }}-user
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
        imagePullPolicy: {{ .Values.user.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.user.service.internalPort }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: {{ .Values.user.service.internalPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.user.service.internalPort }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
