{{- if .Values.admin.ingress.enabled -}}
{{- $serviceName := include "deltcloud-p1.fullname" . -}}
{{- $servicePort := .Values.admin.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100m
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: {{ template "deltcloud-p1.name" . }} -admin
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "deltcloud-p1.fullname" . }}-admin
spec:
  rules:
    {{- range $host := .Values.admin.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}-admin
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.admin.ingress.tls }}
  tls:
{{ toYaml .Values.admin.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
