apiVersion: v1
kind: Service
metadata:
  name: {{ template "deltcloud-p1.fullname" . }}-admin
  labels:
    app: {{ template "deltcloud-p1.name" . }}-admin
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.externalPort }}
      targetPort: {{ .Values.admin.service.internalPort }}
      protocol: TCP
      name: {{ .Values.admin.service.name }}
  selector:
    app: {{ template "deltcloud-p1.name" . }}-admin
    release: {{ .Release.Name }}
