apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "netbank-cs.fullname" . }}-nginx
  labels:
    app: {{ template "netbank-cs.name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "netbank-cs.name" . }}-nginx
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx.service.internalPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "netbank-cs.fullname" . }}-nginx
