apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "netbank-cs.name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "netbank-cs.fullname" . }}-nginx
data:
  default.conf: |-
{{ .Values.nginx.confFiles | indent 4 }}
