apiVersion: v1
kind: Service
metadata:
  name: {{ template "netbank-cs.fullname" . }}-nginx
  labels:
    app: {{ template "netbank-cs.name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.externalPort }}
      targetPort: {{ .Values.nginx.service.internalPort }}
      protocol: TCP
      name: {{ .Values.nginx.service.name }}
  selector:
    app: {{ template "netbank-cs.name" . }}-nginx
    release: {{ .Release.Name }}
