apiVersion: v1
kind: Service
metadata:
  name: {{ template "netbank-cs.fullname" . }}-phone
  labels:
    app: {{ template "netbank-cs.name" . }}-phone
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.phone.service.type }}
  ports:
    - port: {{ .Values.phone.service.externalPort }}
      targetPort: {{ .Values.phone.service.internalPort }}
      protocol: TCP
      name: {{ .Values.phone.service.name }}
  selector:
    app: {{ template "netbank-cs.name" . }}-phone
    release: {{ .Release.Name }}
