apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "netbank-chat.fullname" . }}-api
  labels:
    app: {{ template "netbank-chat.name" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "netbank-chat.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.internalPort }}
          volumeMounts:
          - name: config
            mountPath: /tigase_api/conf
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
    {{- if .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.api.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "netbank-chat.fullname" . }}-api
          items:
          - key: config
            path: app.conf

