# Default values for netbank-customer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/usersvr
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  name: netbank-customer
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi


mariadb:
  mariadbDatabase: nbusers
  mariadbUser: netbank
  mariadbPassword: netbank


sms:
  smsAccessKeyId: smsAccessKeyId
  smsSecret: smsSecret
  smsRegisterTemplate: smsRegisterTemplate
  smsResetPwdTemplate: smsResetPwdTemplate

captchaHost: captcha-0-captcha
