apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}
data:
  alertmanager.rules.yaml: |
    {{ toYaml  .Values.rules | indent 4 }}

  prometheus.yml: |-
    global:
      scrape_timeout: 50s
    alerting:
      alertmanagers:
        - static_configs:
          - targets: ["{{ template "prometheus.alertmanager.fullname" . }}"]
    rule_files:
      - /etc/config/alertmanager.rules.yaml
    scrape_configs: |
      {{- if .Values.jobs -}}
        {{ toYaml  .Values.jobs | indent 6 }}
      {{- end -}}
    {{- if .Values.remote_storage.enabled }}
    remote_write:
      - url: "http://{{ template "prometheus.influxdb.fullname" . }}:8086/api/v1/prom/write?u={{ .Values.influxdb.setDefaultUser.user.username }}&p={{ .Values.influxdb.setDefaultUser.user.password }}&db={{ .Values.influxdb.dbName }}"
    remote_read:
      - url: "http://{{ template "prometheus.influxdb.fullname" . }}:8086/api/v1/prom/read?u={{ .Values.influxdb.setDefaultUser.user.username }}&p={{ .Values.influxdb.setDefaultUser.user.password }}&db={{ .Values.influxdb.dbName }}"
    {{- end -}}
