## harboar configuration

ui_secret: "R0pgaboUszpAkhQ0"
jobservice_secret: "l5wzTaD2RyuwKIIw"
secret_key: "lY7sfY5AwPZtcsTz"

pkey: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA2illcwdkJTHhQx1WAOLs44hjWXoZ93DD/a/SwZh51vkrR6s6
  Ra1AzXymPrrWOHSKwY5lsSKCMTpLr49VXbp8xekxCY0xpfpPxR8D6U13ZU1vQ9xa
  E5ztNfZgcZ8J9+DMO9AaKfUR4PrqeofIKgq3y9pyzv+rJGaHcKLD7vdu2fyeuUC8
  A5o0wMxKdrpCBs2DLtGW3p3eIAprBhA5qTV+zRawnGLmsYDlJcQ2xeDGGzSjLm5R
  Z4UcwGfiTbsjXyRaelIhxMaxwZaXOq8OghTyJj4dcSiFXArysdmjX+EPNojQ0TNP
  msChI7BZiW8K7OP4wwoXBlrnX6ViCX+RGtEfv+WYs3il92MXzJzy0ve+XOm9EEGu
  RGEVfrcpGWlpGgZWm2+MphP5R/uGFb3Mc8N0pqJA/wtKtO3hdWnlpLbmWZaBwNJA
  WPEAppYaAVpLx5hnfDX1fgbHUi++dffO1kO5ADKXsA+bQX3H2rl+pxztFrvXHVw0
  /4F6+AD46+PLFFEv3/hffFdpNkH8BI6AnsmNGuBMOevbSI51LRcoufTOgP+BmBah
  PH8L7lMF8l4LabP1YojAem/gDwy4GpLU8AHI2wOosRdano7kDrDlo/Q8NNUpSpfg
  +zZqxkCNr3Yqc8lOvqIXUVdD5RNgdkJNhql2g5vC50PqE9A1aQRURvDBhAMCAwEA
  AQKCAgBlZXAdcoX9M527D9t1NgNcDXv/jlybQPIW6q1OBYw7eju/Z7oBwHCqERFD
  fpsqSiBjrcdd+OgB8VJUGo5WreJoKeX8xn8Y4apJuAydVr/zeXYJWFUVYI5v0j8p
  D/4WE4lZE3PVpG3W30g0Av/pamnaeYF67CGjHXQ9yai/XIlND7jF6Wx5UCbMpSbG
  3/LoLoSWMhupBD7FLZJokwn5tz9kGvOi++S1A299iiDa/4mUA3cEkYmMT7X5R09L
  SXs7MS5MQ/gl+SONEmzffZWEqC+TzrLocSjqirwaJUllurjTY+uKEAsjpfw/FivH
  ULEHQT3RiNMCxSVcswVJ3NyYVjImpt/hANDFOHVqzfvRFEYwG4hiLQR/bHeKdWA/
  EkUcZt6V6jqyYzV4VOp0d05kQtWJu6ArVqTzAyL56CdmpJ7BheYO5hkIbNhBh9rD
  rYj+6SArrYkl2wZmcKJOkn6GrdHiwzlae6L9NLM92Giu77q1eEiGl+wl7BrnLZeX
  T/DAG6lXHNkWvLF0MG5sdz+aI/mdjVfC38ph/sme1if9eu6mr//k4EL7lpUK3eKP
  gMnHTEQ3I952zppilf2wgii3pGT9aC9HZht+/+gt7yOKEw4rJMtQJkY4dzv/MT22
  hGqyvicdrfjbQs5Dw+flNVWdNSCznWhrEhTM8ZNo0dTEqZQ3QQKCAQEA78ns9p0t
  SRIL4ywA0QMJgmowXlKJsV3KT6EYYIgJQ8hJ9uXiCjhpPuEabz68nQw97J4VMl74
  2fxETQLBcDlFIgsAbtkrAgWlDk864qvBN325Rczv1TBdD1z6U8QYacbqfoKeXCw4
  m0EjOdxOyDrLmx/f8+I59DVzHrejkDziTdxAAsJpweLsz4wwRwCTUi15GjM5ZQum
  JDwvZBCjHVxbPfgaAF5iX+eWjnsDxnn/zNUCWsguw9G9X3ucLqTyda6D6zGRdjrG
  cbhlVOJ88y6ZYA/xCdu0WEOHnzZB1w3tCsf5ZkGw9YYdM7Ot9ORkWNFmUfgC3zGH
  SYcBDsejLMKbWwKCAQEA6Okqnbh1k3YtWZuHawQJu3+sPUN8r9xbcaCkZXYSLA6q
  JfrfWniYdJyQymlPmMK8RhOKwJzabxV1VK5Rz7lu6kOt5aw+MFPwWczlqYIiiFIr
  +sZURMiIFAlpLYefQZWysISQs2veF4mv+JqEgFGQlzxPDZlrwaQozOJnw1WVHW+B
  HQutyGMDrJLiliG8KlLPiVbSz2GnyLEpRSxuW6FVVixuUaGn2Yw1uMxOnDJO211D
  O9/MnwkqX8/jE/+h/xqx4zV4q+QyYgbePvzbCiDAPnuj+KuPtJkFTSegKjZARiis
  6zss+XrCPcYwK9YaDjvRKOFg5Jq0V+Ha2sa13awieQKCAQEAlEJsklrCakCPOwm1
  A4Z2Nb2EZH1yB0lvUmbPlLfnypInMVIXvav9XtR9rLTEl/G+w/NGNdvEz7sLW/ZN
  Nh8i4Jae0OrTja+By2Qvi4EYuT+x8zdwPodlsp8RZAOF+Lj1ufz2/xSUd2IB7r+J
  soGv7Bz8MmX44Ua/BAoVRpRudCevKEWecDPnqbgLDYuMiy30h7+OSCy4sATKZHto
  7zlwbNNe+EVjW9rsGvJydiBuie5WQ10slQS0qznZanmwNBUQGbaPMuPKWPvjI2Xa
  Td3NFTkmFqtSSZSPYWCBuv8wRg845AHP8S7YFWSONTGV3dizBBFtbSTJeivP+pxz
  BrTYqwKCAQAqf1DtUljxvSBtNzmwRx5XfeY5j3TSycxNoVgdwztxmoNlRq82XMbE
  kETDChAh+XZM+wfYOUaJ+kpcVypKUrVwPUUfoRv/yXETkZVeJoaShRvNOB7sJgLe
  VRFB43slhmECYE3ezxHJDbB0Fg2TNE7DqZdrDdFhlch0CeOQ+q6onk3atOTSqW5k
  MLDzX9hriIyhrJvuhw0MS3cSThcc1QUzIgxHDM4JndG3lF/LlEpbMFsyM5Wsdwmq
  Tc5LOdufJonKwVjxVEP1KvemWpDE+lDZlcnHd9ZSx5D2EQLicN+tbYKPsU51fvau
  OtlTRk+exT9WzDjXvXqmhmlefd91QRFRAoIBAQCoYeRTPiQnxHv25SpRR70qfhPS
  2wqZJ3ZW4AKFGRTQ2A8POZf8gRkSFxVUTdN+33c5EIYPapRYJA2jYBO5S/kDvU+A
  tO8lEMG0uYJziLswCejciuTjT5vr0pQtZMMN/AwSmunobMQ8MoXwfLuDiEAQA002
  oOO30B8ajO/v4AvXtYC94dprvhusZ8HYG4n6HLfys30MtsVW758A68GZXDh1NoAr
  y5LzNemZYS9GkSn18fh3iA6SsrhZl49vacoC6ymS8wAzzBNlv+BvNfQ4P8kcSuBu
  /wwRMd4lSmZVGT3oXls1ft6txPJB0a8Upyx5mjb5wfyc4edmx0A5/gZTPSV7
  -----END RSA PRIVATE KEY-----
  
cert:
  -----BEGIN CERTIFICATE-----
  MIIE0zCCArugAwIBAgIJAI5RM8dAcsmOMA0GCSqGSIb3DQEBCwUAMAAwHhcNMTcx
  MjEyMTQ0MDA3WhcNMjcxMjEwMTQ0MDA3WjAAMIICIjANBgkqhkiG9w0BAQEFAAOC
  Ag8AMIICCgKCAgEA2illcwdkJTHhQx1WAOLs44hjWXoZ93DD/a/SwZh51vkrR6s6
  Ra1AzXymPrrWOHSKwY5lsSKCMTpLr49VXbp8xekxCY0xpfpPxR8D6U13ZU1vQ9xa
  E5ztNfZgcZ8J9+DMO9AaKfUR4PrqeofIKgq3y9pyzv+rJGaHcKLD7vdu2fyeuUC8
  A5o0wMxKdrpCBs2DLtGW3p3eIAprBhA5qTV+zRawnGLmsYDlJcQ2xeDGGzSjLm5R
  Z4UcwGfiTbsjXyRaelIhxMaxwZaXOq8OghTyJj4dcSiFXArysdmjX+EPNojQ0TNP
  msChI7BZiW8K7OP4wwoXBlrnX6ViCX+RGtEfv+WYs3il92MXzJzy0ve+XOm9EEGu
  RGEVfrcpGWlpGgZWm2+MphP5R/uGFb3Mc8N0pqJA/wtKtO3hdWnlpLbmWZaBwNJA
  WPEAppYaAVpLx5hnfDX1fgbHUi++dffO1kO5ADKXsA+bQX3H2rl+pxztFrvXHVw0
  /4F6+AD46+PLFFEv3/hffFdpNkH8BI6AnsmNGuBMOevbSI51LRcoufTOgP+BmBah
  PH8L7lMF8l4LabP1YojAem/gDwy4GpLU8AHI2wOosRdano7kDrDlo/Q8NNUpSpfg
  +zZqxkCNr3Yqc8lOvqIXUVdD5RNgdkJNhql2g5vC50PqE9A1aQRURvDBhAMCAwEA
  AaNQME4wHQYDVR0OBBYEFCJ6f7aSbNgkDgYRA8mkjVx+QQtiMB8GA1UdIwQYMBaA
  FCJ6f7aSbNgkDgYRA8mkjVx+QQtiMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEL
  BQADggIBAKWBQlmo44MpDZgS6c1VGpI4m2R2itS1YpbTBLZxqa0ArVVg0mKfJNkb
  E1upl8dMCOMzdqTA2sy7FxfppztugaSCE02WXSz46yJ/T0CEFaDwl64cADjRMO2B
  wzYtFxszYFrfkuv9P3Bx8dbvf9hrTvrI/KDp0toWwOkrwfr6hpqOsv+W6pP2n+Ur
  1Jtqt8pbTUUewjMoVUON63o1m5kQDrEgvPXhZYATAhIAKmggw+beJZ7MMZikG+qW
  1ZplODRjolQJxyR5NhYXlRoj1H+bqgt/eLwYSLUbqJ2P3PFLGtWgIt3wx/CjMVyo
  bvwEel9js+mhz6fLcONbijp0qSyMLX8cJbdDt38TWV6LBTXe2DXSj330xHH046P0
  0Eg1Xbz85Iwmjar7jP60VymOZAZVPv5P4heo5BudwKh9LEgLinlTgaXpgY0rn7Mu
  2twtzEY3xXLX45kem5DYETfl88qYK74E8WbEzqVunWB2YEkwnGkCDe4rRg4xRH9u
  cwZ36a0W88znlh+1/Y5X55dvoBTzdjo17dwYf9MoZICUL7AsiDe0+vymS9bTOX5k
  deEB+qdgyUe5VaJtCikofcfilMek0BEwyWFhWx6rP3yfRz9NGtHGeByZ3FMR1jhy
  P8QEzBYqiTm/iFyGOj5WzH9d3TKd5hRtgz5wTia966CGjqsQFNr6
  -----END CERTIFICATE-----

#max_job_workers "3"

## defaut log level debug
#log_level: "debug"

#godebug: "netdns=cgo"

service:
  host: "reg.1.k8s.linkcloud.cn"
  # support Ingress,NodePort,LoadBalance.If type is Ingress, ingress is a necessary felid. If type is NodePort, externalPort is a necessary felid.
  # annotations.nginx.org/client-max-body-size default is 1m we should change it to match image size needs.
  type: Ingress
  externalPort: 31000
  ingress:
    tls: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/proxy-body-size: 600m

nginx:
  replicaCount: 1
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/nginx
    tag: 1.11.5
    pullPolicy: IfNotPresent
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

ui:
  replicaCount: 1
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/harbor-ui
    tag: v1.2.2
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  # harbor admin default Password is "Harbor12345"
  # adminPassword: "Harbor12345"
  #email_server = smtp.mydomain.com
  #email_server_port = 25
  #email_username = sample_admin@mydomain.com
  #email_password = abc

registry:
  replicaCount: 1
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/registry
    tag: 2.6.2-photon
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  persistence:
    enabled: true
    storageClass: ceph-rbd
    accessMode: ReadWriteOnce
    size: 8Gi

jobservice:
  replicaCount: 1
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/harbor-jobservice
    tag: v1.2.2
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  persistence:
    enabled: true
    storageClass: ceph-rbd
    accessMode: ReadWriteOnce
    size: 8Gi

mysql:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/harbor-db
    tag: v1.2.2
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  # mysql root default Password is "root123"
  # rootPassword: "root123456"
  persistence:
    enabled: true
    storageClass: ceph-rbd
    accessMode: ReadWriteOnce
    size: 8Gi

adminserver:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/linkcloud/harbor-adminserver
    tag: v1.2.2
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

