apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "netbank-customer.fullname" . }}
  labels:
    app: {{ template "netbank-customer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data: 
  config: |-
    appname = usersvr
    httpport = {{ .Values.service.internalPort }}
    runmode = dev
    autorender = false
    copyrequestbody = true
    EnableDocs = true

    dbhost={{ template "netbank-customer.fullname" . }}-mysql
    dbschema={{ .Values.mysql.mysqlDatabase }}
    dbuser={{ .Values.mysql.mysqlUser }}
    dbpassword={{ .Values.mysql.mysqlPassword }}
    dbport={{ .Values.mysql.service.externalPort }}
    copyrequestbody=true


    publicKeyPath=key.pub

    smsAccessKeyId={{ .Values.sms.smsAccessKeyId }}
    smsSecret={{ .Values.sms.smsSecret }}
    smsSignature={{ .Values.sms.smsSignature}}
    smsRegisterTemplate= {{ .Values.sms.smsRegisterTemplate }}
    smsResetPwdTemplate= {{ .Values.sms.smsResetPwdTemplate }}

    captchaHost=http://{{ .Values.captchaHost }}/verify
    tigaseHost=http://tigase:8080/rest/adhoc/sess-man@im.linkcloud.cn?api-key=test1234
    tigaseAuthorization=Basic YWRtaW5AaW0ubGlua2Nsb3VkLmNuOmFkbWlu
    tigaseDomain=im.linkcloud.cn
    
    7niuBucket=zhenhaip
    7niuAK=NDj32L53COMvyU72IY3pdgZhc5GAjMDaqeHXugkp
    7niuSK=5yOxgmQgT0HjMo1ZtqfjllTRrm1xsIW5Q2NdIe2E
    7niuForeignDomain=http://7nj2q4.com1.z0.glb.clouddn.com

