apiVersion: v1
kind: Service
metadata:
  name: {{ template "netbank-customer.fullname" . }}-mysql
  labels:
    app: {{ template "netbank-customer.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.externalPort }}
      targetPort: {{ .Values.mysql.service.internalPort }}
      protocol: TCP
      name: {{ .Values.mysql.service.name }}
  selector:
    app: {{ template "netbank-customer.name" . }}-mysql
    release: {{ .Release.Name }}
