issuer: "http://auth.netbank.cn"
token_url: token.example.com
client_url: client.example.com
image: registry.cn-hangzhou.aliyuncs.com/linkcloud/dex
imageTag: 1.0.0
imagePullPolicy: "IfNotPresent"


postgresql:
  image: "registry.cn-hangzhou.aliyuncs.com/linkcloud/postgres"
  imageTag: "9.6.2"
  imagePullPolicy: "IfNotPresent"
  postgresUser: dex
  postgresPassword: "dex123"
  postgresDatabase: dex_db
  persistence:
    storageClass: default
    size: 8Gi

configfile:
  issuer: http://auth.netbank.cn
  storage:
    type: postgres
    config:
      Host: postgres
      database: dex_db
      user: dex
      password: dex123
      ssl:
        mode: disable
  web:
    http: 0.0.0.0:5556
    AllowedOrigins: ["*"]
  OAuth2:
    SkipApprovalScreen: true
    responseTypes: ["code", "token", "id_token"]
  PrivateKeyPath: ./bin/key/pkcs1_private.pem
  grpc:
    addr: 0.0.0.0:5557
    tlsCert: ./bin/key/server.crt
    tlsKey: ./bin/key/server.key
    tlsClientCA: ./bin/key/ca.crt
  connectors:
  - type: grpc
    id: grpc
    name: grpc
    config:
      endpoint: "127.0.0.1:50051"
  enablePasswordDB: false
