issuer: "http://auth.netbank.cn"
customer_service: "http://netbank-customer:8080"
token_url: token.example.com
client_url: client.example.com
image: registry.cn-hangzhou.aliyuncs.com/linkcloud/dex
imageTag: 1.0.0
imagePullPolicy: "IfNotPresent"


postgresql:
  image: "registry.cn-hangzhou.aliyuncs.com/linkcloud/postgres"
  imageTag: "9.6.2"
  imagePullPolicy: "IfNotPresent"
  postgresUser: dex
  postgresPassword: "dex123"
  postgresDatabase: dex_db
  persistence:
    storageClass: default
    size: 8Gi

