apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "netbank-dems.fullname" . }}-cmdb
  labels:
    app: {{ template "netbank-dems.name" . }}-cmdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.cmdb.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "netbank-dems.name" . }}-cmdb
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cmdb.image.repository }}:{{ .Values.cmdb.image.tag }}"
          imagePullPolicy: {{ .Values.cmdb.image.pullPolicy }}
          env:
          - name: MYSQL_HOST 
            value: {{ template "netbank-dems.name" . }}-mariadb
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mariadb.mariadbRootPassword }}
          - name: MYSQL_SCHEMA
            value: {{ .Values.mariadb.mariadbDatabase }}
          ports:
            - containerPort: {{ .Values.cmdb.service.internalPort }}
    {{- if .Values.cmdb.livenessProbe  }}
          livenessProbe:
{{ toYaml .Values.cmdb.livenessProbe | indent 10 }}
    {{- end }}
    {{- if .Values.cmdb.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.cmdb.readinessProbe | indent 10 }}
    {{- end }}
          resources:
{{ toYaml .Values.cmdb.resources | indent 12 }}
    {{- if .Values.cmdb.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cmdb.nodeSelector | indent 8 }}
    {{- end }}
