apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "netbank-dems.name" . }}-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "netbank-dems.fullname" . }}-ui
data:
{{ toYaml .Values.ui.confFiles | indent 2 }}
